swift_book_pdf/latex_helpers.py

Fixes an issue where external URLs were not being rendered as footnotes in `print` mode.

fix: Show external links in URLs in footnotes (`print` mode)

---

README.md
swift_book_pdf/book.py
swift_book_pdf/cli.py
swift_book_pdf/config.py
swift_book_pdf/files.py
swift_book_pdf/fonts.py
swift_book_pdf/log.py

Introduces improvements to console logging:
- When the log level is set to INFO, git clone logs are no longer presented.
- The “Creating PDF...” log line now displays the rendering mode.
- LaTeX scrolling logs now show up to 10 lines.
- When the log level is set to DEBUG, LaTeX logs are presented in full.

chore: Streamline console logging

---

CHANGELOG.md
README.md
swift_book_pdf/book.py
swift_book_pdf/cli.py
swift_book_pdf/config.py
swift_book_pdf/doc.py
swift_book_pdf/latex.py
swift_book_pdf/preamble.py
swift_book_pdf/schema.py
swift_book_pdf/toc.py

Adds support for generating the TSPL book in legal and A4 sizes. Adds `—-size` CLI option to set the paper size. Changed the footer's bottom margin to mirror the header's top margin.
To maintain the same text box width, the book gutter for the A4 size has been decreased to 1.67 inches vs the standard 1.9 inch gutter in letter/legal paper sizes.

feat: Add support for different page sizes

---

CHANGELOG.md
swift_book_pdf/book.py
swift_book_pdf/cli.py
swift_book_pdf/config.py
swift_book_pdf/fonts.py
swift_book_pdf/latex.py
swift_book_pdf/latex_helpers.py
swift_book_pdf/preamble.py

The current font requirements to typeset TSPL are quite macOS-centric. swift-book-pdf will now typeset TSPL in any system where LuaTeX has access to at least one font in each of the following font categories:
* **Main Font:** Helvetica Neue, Helvetica, SF Pro, Arial, Segoe UI, Liberation Sans, DejaVu Sans
* **Unicode Font:[^1]** Arial Unicode MS, Noto Sans CJK, Noto Serif CJK
* **Mono Font:** Menlo, SF Mono, Courier, Monaco, Consolas, Courier New, DejaVu Sans Mono, Ubuntu Mono
* **Emoji Font:** Apple Color Emoji, Segoe UI Emoji, Noto Color Emoji
* **Header & Footer Font:** SF Compact Display, SF Pro Display, SF Compact, SF Pro, Helvetica Neue, Helvetica, SF Pro, Arial, Segoe UI, Liberation Sans, DejaVu Sans
This change should make it easier for Windows and Linux users to generate a PDF …

Add more default font choices for each required font category

---

.github/ISSUE_TEMPLATE/01-font-bug-report.yaml
CHANGELOG.md
swift_book_pdf/cli.py
swift_book_pdf/fonts.py
swift_book_pdf/log.py
swift_book_pdf/pdf.py

- Adds the option to specify custom fonts for each of the five font categories introduced in #12. 
- swift_book_pdf will verify that such fonts are available to LuaTeX before typesetting. 
- An error is raised when a font (custom or default) does not support a typeset character based on the assigned font category. 
- Adds `--version` option and issue template for font issue reporting.

feat: Add option to set custom fonts

---

CHANGELOG.md
swift_book_pdf/pdf.py

Adds the `--enable-write18` option in the `lualatex` call, in addition to `--shell-escape`.
From the [minted docs](https://ctan.math.illinois.edu/macros/latex/contrib/minted/minted.pdf) (p.8):
> For versions of TeX Live before 2024 and for MiKTeX, latexminted requires special permission to run. This can be accomplished by running LaTeX with the `--shell-escape` option (TeX Live) or the `--enable-write18` option (MiKTeX).

fix/ Add shell escape option for MiKTeX

---

CHANGELOG.md
poetry.lock
pyproject.toml
swift_book_pdf/latex_helpers.py
swift_book_pdf/preamble.py

Removes special handling of Unicode + Emoji characters and relies on fallback fonts to render all characters. This change makes it easier to fall through all available fonts in case we can render the character with one of the other available fonts.
There are still some characters, however, that require special handling before typesetting. Currently, the only character in this category is é⃝, which is typeset as `\textcircled{é}`. See the new `override_characters` function.

feat/ Better Unicode + Emoji character handling

---

CHANGELOG.md
swift_book_pdf/latex_helpers.py

Fixes an issue where image paths passed to LaTeX were not following the Unix style on Windows.

fix/ Incorrect asset paths on Windows

---

CHANGELOG.md
swift_book_pdf/book.py
swift_book_pdf/latex_helpers.py

Fixes an issue where the output file could not be saved by overwriting an existing file in Windows systems.

fix/ Cannot overwrite existing file on Windows

---

CHANGELOG.md
swift_book_pdf/cli.py
swift_book_pdf/fonts.py
swift_book_pdf/preamble.py

Fixes an issue where an accepted Unicode font may not support all required glyphs. Adds a new "Global" font category as a unicode font for additional characters not supported by the main font, e.g. Chinese characters. The same font can be used both for Global and Unicode categories if it includes all required glyphs (e.g. Arial Unicode MS).

fix/ Accepted Unicode fonts may not be all-encompassing

---

CHANGELOG.md
swift_book_pdf/log.py

Fixes an issue where the LaTeX typesetting process may continue even after a font error is raised.

fix/ Kill LaTeX process when a font issue is raised

---

CHANGELOG.md
swift_book_pdf/fonts.py

Fixes an issue where fonts names may be incorrectly recognized as available to LuaTeX because of partial name matches. For example, font Courier would be marked as available if luaotfload-tool returned Courier New as an available font.

Fix/ Better font detection

---

CHANGELOG.md
swift_book_pdf/latex.py
swift_book_pdf/markdown_helpers.py

Fixes an issue where some reference-style Markdown links may be missing from the LaTeX document.

Fix/ Missing reference-style links

---

swift_book_pdf/markdown_helpers.py

Fixes an issue where the incorrect label would be displayed for reference-style links.

fix/ Rely on first reference-style name for external links

---

CHANGELOG.md
poetry.lock
pyproject.toml
swift_book_pdf/pdf.py

Add `latexminted` package dependency to ensure that `minted` v3 can run correctly on all systems. Only use shell escape when using an unsupported system (TeX Live < 2024 or MiKTeX).

chore/ Add `latexminted` dependency & shell escape optimizations

---

CHANGELOG.md
swift_book_pdf/latex_helpers.py

Change regular expression used for detecting URLs in Markdown that may have caused exponential backtracking on strings starting with '[\](http://' and containing many repetitions of '!'.

fix/ Inefficient regular expression

---

CHANGELOG.md
swift_book_pdf/cli.py
swift_book_pdf/config.py
swift_book_pdf/files.py
swift_book_pdf/pdf.py
swift_book_pdf/schema.py

Adds new `--input-path`/`-i` option to use local copy of the swift-book repo. If not provided, the repository will still be cloned from GitHub.

feat/ Option to use local version of the `swift-book` repo

---

CHANGELOG.md
swift_book_pdf/pdf.py

Fixes an issue where some 2024 TeX Live installations may not be able to typeset TSPL because minted still requires the `-shell-escape` option. Add a new detection mechanism for the minted requiring shell escape by typesetting a simple document containing a minted box.

fix/ Better `minted` shell escape detection mechanism

---

CHANGELOG.md
README.md
swift_book_pdf/cli.py
swift_book_pdf/doc.py
swift_book_pdf/preamble.py

Resolves #9 by adding a new `--gutter`/`--no-gutter` option to control whether the typeset document has a book gutter and different layout for left/right pages.

feat/ Option for typesetting without book gutter

---

README.md

Removes direct instructions from README and redirects to Wiki guides for more detailed information, including the new Customization page.

docs/ Redirect to Wiki guides from README

---

swift_book_pdf/book.py

This fixes the error when the output folder is not on the system's root partition (#44, #45)

Use shutil.move instead of os.replace
